name: cojob
description: "Work environment communication app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.8.3
  http: ^1.2.0
  bloc: ^8.1.3
  google_fonts: ^5.0.0
  flutter_secure_storage: ^9.0.0
  table_calendar: ^3.1.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/
  uses-material-design: true
